{{- if .Values.testService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama-test
  template:
    metadata:
      labels:
        app: llama-test
    spec:
      runtimeClassName: wasmedge
      containers:
        - name: llama-api-server
          image: ghcr.io/second-state/llama-api-server:latest
          imagePullPolicy: Never
          command: ["llama-api-server.wasm"]
          args:
            - "--prompt-template"
            - "llama-3-chat"
            - "--ctx-size"
            - "4096"
            - "--model-name"
            - "llama-3-3b-uncensored"
          env:
            - name: WASMEDGE_PLUGIN_PATH
              value: "{{ .Values.paths.wasi_nn_plugin_file_dir }}"
            - name: LD_LIBRARY_PATH
              value: "{{ .Values.paths.wasi_nn_plugin_lib_dir }}"
            - name: WASMEDGE_WASINN_PRELOAD
              value: "default:GGML:CPU:/home/dev/models/Llama-3.2-3B-Instruct-Uncensored-Q5_K_M.gguf"
          volumeMounts:
            - name: gguf-model-file
              mountPath: /home/dev/models/Llama-3.2-3B-Instruct-Uncensored-Q5_K_M.gguf
              readOnly: true
            - name: wasi-nn-plugin-file
              mountPath: {{ .Values.paths.wasi_nn_plugin_file }}
              readOnly: true
            - name: wasi-nn-plugin-lib-dir
              mountPath: {{ .Values.paths.wasi_nn_plugin_lib_dir }}
              readOnly: true
{{- range .Values.systemLibs }}
            - name: {{ .name }}
              mountPath: {{ .hostPath }}
              readOnly: true
{{- end }}
      volumes:
        - name: gguf-model-file
          hostPath:
            path: /home/dev/models/Llama-3.2-3B-Instruct-Uncensored-Q5_K_M.gguf
            type: File
        - name: wasi-nn-plugin-file
          hostPath:
            path: {{ .Values.paths.wasi_nn_plugin_file }}
            type: File
        - name: wasi-nn-plugin-lib-dir
          hostPath:
            path: {{ .Values.paths.wasi_nn_plugin_lib_dir }}
            type: Directory
{{- range .Values.systemLibs }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: File
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: llama-test-service
  labels:
    llamaedge/target: "true"
  annotations:
    llamaedge/weight: "2"
spec:
  selector:
    app: llama-test
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
{{- end }}